version: "3"
services:
  redis:
    container_name: "redis-server"
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-volume:/data
  db:
    container_name: "db-server"
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql-volume:/var/lib/mysql
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /var/www/my-stuff/node_modules
      - /var/www/my-stuff/packages/common/config/node_modules
      - /var/www/my-stuff/packages/common/constants/node_modules
      - /var/www/my-stuff/packages/client/app/node_modules
      - /var/www/my-stuff/packages/client/common/node_modules
      - /var/www/my-stuff/packages/client/modules/node_modules
      - /var/www/my-stuff/packages/client/utils/node_modules
      - /var/www/my-stuff/packages/core/middlewares/node_modules
      - /var/www/my-stuff/packages/core/migrations/node_modules
      - /var/www/my-stuff/packages/core/models/node_modules
      - /var/www/my-stuff/packages/core/redis/node_modules
      - /var/www/my-stuff/packages/core/repositories/node_modules
      - /var/www/my-stuff/packages/core/server/node_modules
      - /var/www/my-stuff/packages/core/services/node_modules
      - /var/www/my-stuff/packages/core/utils/node_modules
      - ./common:/var/www/my-stuff/common:cached
      - ./client:/var/www/my-stuff/client:cached
      - ./core:/var/www/my-stuff/core:cached
      - ./public:/var/www/my-stuff/public:cached
volumes:
  redis-volume:
  mysql-volume:
