version: "3"
services:
  redis:
    container_name: "redis-server"
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-volume:/data
  db:
    container_name: "db-server"
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql-volume:/var/lib/mysql
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
  api-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - CLIENT_HOST=http://client
      - DB_HOST=db
      - REDIS_HOST=redis
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      - redis
volumes:
  redis-volume:
  mysql-volume:
