version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static:/usr/share/nginx/html
  client:
    command: ["yarn", "build:client"]
    volumes:
      - static:/var/www/my-stuff/dist
  server:
    command: ["yarn", "build:server"]
volumes:
  static:
