version: "3"
services:
  redis:
    container_name: "redis-server"
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-volume:/data
  mongodb:
    container_name: "mongo-server"
    image: "bitnami/mongodb:latest"
    restart: always
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongodb-volume:/bitnami
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - NODE_ENV=development
  api-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - CLIENT_HOST=http://client
      - DB_HOST=mongodb
      - REDIS_HOST=redis
      - NODE_ENV=development
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - mongodb
volumes:
  redis-volume:
  mysql-volume:
  mongodb-volume:
