version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - static:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api-server
  client:
    build:
      context: .
      dockerfile: Dockerfile.client.prod
    volumes:
      - static:/var/www/my-stuff/dist
  api-server:
    build:
      context: .
      dockerfile: Dockerfile.server.prod
volumes:
  static:
