const MODULE = 'ADMIN';

export const GET_PRODUCTS_PENDING = `${MODULE}/GET_USERS/PENDING`;
export const GET_PRODUCTS_SUCCESS = `${MODULE}/GET_USERS/SUCCESS`;
export const GET_PRODUCTS_FAILURE = `${MODULE}/GET_USERS/FAILURE`;
