const MODULE = 'ADMIN';

export const GET_PRODUCTS_PENDING = `${MODULE}/GET_PRODUCTS/PENDING`;
export const GET_PRODUCTS_SUCCESS = `${MODULE}/GET_PRODUCTS/SUCCESS`;
export const GET_PRODUCTS_FAILURE = `${MODULE}/GET_PRODUCTS/FAILURE`;

export const COUNT_PRODUCTS_PENDING = `${MODULE}/COUNT_PRODUCTS/PENDING`;
export const COUNT_PRODUCTS_SUCCESS = `${MODULE}/COUNT_PRODUCTS/SUCCESS`;
export const COUNT_PRODUCTS_FAILURE = `${MODULE}/COUNT_PRODUCTS/FAILURE`;

export const PRODUCTS_PAGE_CHANGE = `${MODULE}/PRODUCTS_PAGE_CHANGE`;
export const PRODUCTS_PER_PAGE_CHANGE = `${MODULE}/PRODUCTS_PER_PAGE_CHANGE`;
