const MODULE = 'ADMIN';

export const GET_PRODUCTS_PENDING = `${MODULE}/GET_PRODUCTS/PENDING`;
export const GET_PRODUCTS_SUCCESS = `${MODULE}/GET_PRODUCTS/SUCCESS`;
export const GET_PRODUCTS_FAILURE = `${MODULE}/GET_PRODUCTS/FAILURE`;

export const COUNT_PRODUCTS_PENDING = `${MODULE}/COUNT_PRODUCTS/PENDING`;
export const COUNT_PRODUCTS_SUCCESS = `${MODULE}/COUNT_PRODUCTS/SUCCESS`;
export const COUNT_PRODUCTS_FAILURE = `${MODULE}/COUNT_PRODUCTS/FAILURE`;

export const GET_PRODUCT_DETAILS_PENDING = `${MODULE}/GET_PRODUCT_DETAILS/PENDING`;
export const GET_PRODUCT_DETAILS_SUCCESS = `${MODULE}/GET_PRODUCT_DETAILS/SUCCESS`;
export const GET_PRODUCT_DETAILS_FAILURE = `${MODULE}/GET_PRODUCT_DETAILS/FAILURE`;

export const PRODUCT_EDIT_MODE_ENABLED = `${MODULE}/PRODUCT_EDIT_MODE_ENABLE`;
export const PRODUCT_EDIT_MODE_DISABLED = `${MODULE}/PRODUCT_EDIT_MODE_DISABLE`;

export const PRODUCT_UPDATE_PENDING = `${MODULE}/PRODUCT_UPDATE/PENDING`;
export const PRODUCT_UPDATE_SUCCESS = `${MODULE}/PRODUCT_UPDATE/SUCCESS`;
export const PRODUCT_UPDATE_FAILURE = `${MODULE}/PRODUCT_UPDATE/FAILURE`;
