const MODULE = 'AUTH';

export const REGISTER_USER_SUCCESS = `${MODULE}/REGISTER_USER/SUCCESS`;
export const REGISTER_USER_FAIL = `${MODULE}/REGISTER_USER/FAIL`;

export const LOGIN_USER_SUCCESS = `${MODULE}/LOGIN_USER/SUCCESS`;
export const LOGIN_USER_FAIL = `${MODULE}/LOGIN_USER/FAIL`;

export const INITIAL_AUTH_SUCCESS = `${MODULE}/INITIAL_AUTH/SUCCESS`;
export const INITIAL_AUTH_FAIL = `${MODULE}/INITIAL_AUTH/FAIL`;

export const LOGOUT_SUCCESS = `${MODULE}/LOGOUT/SUCCESS`;
export const LOGOUT_FAIL = `${MODULE}/LOGOUT/FAIL`;
